[package]
name = "relay-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
crossterm = "0.27.0"
ratatui = "0.26.2"
serialport = "4.3.0"
shellwords = "1.1.0"
tui-input = "0.8.0"
